### ISSUE TITLE
Fire only visually present

### ISSUE THREAD

**Issue by Tommeh1** [BuiltBrokenModding/SBM-BashFireMakeRock#4]
Whenever you  start a fire you will not receive damage when you stand in it and you will quit burning as soon as you leave it, it also never stops burning until you unload the area and never spreads.
Aside from the chat spam it did however work in the previous version.

**Comment by CraftalotReloaded** [comment]
It's a mod conflict, i have not yet figured out which mod causes it, it ain't foamfix atleast.

**Comment by CraftalotReloaded** [comment]
In the previous version the fire did work fine.

**Comment by Tommeh1** [comment]
In some random rare cases it does work properly though

**Comment by Tommeh1** [comment]
Fixed in last file
